# Generated by Django 4.0.6 on 2022-07-31 02:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_titel_todo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
